In [9]:
import pandas as pd
emp=pd.read_excel(r'/Users/akhil/Projects/Agentic-AI/eda/Rawdata_eda.xlsx')
print(emp)

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [7]:
# emp.shape[0]
emp.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      str
 1   Domain    6 non-null      str
 2   Age       4 non-null      str
 3   Location  4 non-null      str
 4   Salary    6 non-null      str
 5   Exp       5 non-null      str
dtypes: str(6)
memory usage: 619.0 bytes

In [11]:
emp['Name']

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: str

In [14]:
emp['Name']=emp['Name'].str.replace(r'\W', '', regex=True)
print(emp['Name'])

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: str

In [18]:
emp['Age']=emp['Age'].str.extract(r'(\d+)')
(emp['Age'])

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: str

In [19]:
emp['Location']

0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: str

In [30]:
emp['Salary']=emp['Salary'].str.replace(r'\W', '', regex=True)
emp['Salary']
emp['Domain']=emp['Domain'].str.replace(r'\W', '', regex=True)
emp['Domain']

0    Datascience
1        Testing
2    Dataanalyst
3      Analytics
4     Statistics
5            NLP
Name: Domain, dtype: str

In [26]:
emp['Exp']=emp['Exp'].str.extract(r'(\d+)')
emp['Exp']

0      2
1      3
2      4
3    NaN
4      5
5     10
Name: Exp, dtype: str

In [27]:
emp

    Name          Domain  Age   Location Salary  Exp
0   Mike   Datascience#$   34     Mumbai   5000    2
1  Teddy         Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst^^#  NaN        NaN  15000    4
3   Jane     Ana^^lytics  NaN   Hyderbad  20000  NaN
4  Uttam      Statistics   67        NaN  30000    5
5    Kim             NLP   55      Delhi  60000   10

In [31]:
clean_data=emp.copy()
clean_data

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

EDA Techniques :

In [42]:
import numpy as np;

clean_data['Age'] = pd.to_numeric(clean_data['Age'], errors='coerce')
clean_data['Age'] = clean_data['Age'].fillna(clean_data['Age'].mean()).astype(int)

clean_data

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50        NaN  15000    4
3   Jane    Analytics   50   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [43]:
clean_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      str
 1   Domain    6 non-null      str
 2   Age       6 non-null      int64
 3   Location  4 non-null      str
 4   Salary    6 non-null      str
 5   Exp       5 non-null      str
dtypes: int64(1), str(5)
memory usage: 564.0 bytes

In [45]:
clean_data

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50        NaN  15000    4
3   Jane    Analytics   50   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [49]:
clean_data['Exp'] = pd.to_numeric(clean_data['Exp'], errors='coerce')
clean_data['Exp'] = clean_data['Exp'].fillna(clean_data['Exp'].mean()).astype(int)
clean_data

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50        NaN  15000    4
3   Jane    Analytics   50   Hyderbad  20000    4
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [50]:
clean_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      str
 1   Domain    6 non-null      str
 2   Age       6 non-null      int64
 3   Location  4 non-null      str
 4   Salary    6 non-null      str
 5   Exp       6 non-null      int64
dtypes: int64(2), str(4)
memory usage: 557.0 bytes

In [56]:

clean_data['Location'] = clean_data['Location'].replace(4, np.nan)

clean_data['Location'] = clean_data['Location'].fillna(
    clean_data['Location'].mode()[0]
)
clean_data['Location']

0       Mumbai
1    Bangalore
2    Bangalore
3     Hyderbad
4    Bangalore
5        Delhi
Name: Location, dtype: object

In [57]:
clean_data

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50  Bangalore  15000    4
3   Jane    Analytics   50   Hyderbad  20000    4
4  Uttam   Statistics   67  Bangalore  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [58]:
clean_data.to_csv("clean_data.csv", index=False)